import React, {useMemo, useRef, useState} from "react";
import type {Page,Variant} from "./main";
import {variantNames} from "./main";

export const navItems = ["Getting Started","Core Concepts","Node Guides","Regional Prompting","Detailer","Prompt Processing","Pipes & Workflow Data","Node Reference","Regional Prompting","Internal Nodes","Workflow Recipes","BV UI Guide","Compatibility","Troubleshooting"];
const searchEntries = [
  {title:"BV Regional Prompt",kind:"Node Reference",page:"reference" as Page,summary:"Author named V3 regions and prompts."},
  {title:"Build a regional workflow",kind:"Node Guide",page:"guide" as Page,summary:"Wire authoring, capabilities and execution."},
  {title:"Regional System",kind:"Quick Start",page:"home" as Page,summary:"Start with spatial prompting and attention."},
  {title:"Collector not found",kind:"Known Issue",page:"guide" as Page,summary:"Required same-graph collector is missing."}
];
export function Icon({name}:{name:string}) { const g:Record<string,string>={search:"⌕",book:"▤",node:"◇",flow:"⌘",warn:"!",download:"↓",arrow:"→",menu:"☰"}; return <span aria-hidden="true">{g[name]||"✦"}</span>; }
export function DraftPill(){return <span className="draft-pill">V3 development draft</span>}
export function Search({onGo}:{onGo:(p:Page)=>void}) {
  const [query,setQuery]=useState(""); const [open,setOpen]=useState(false);
  const results=useMemo(()=>query?searchEntries.filter(x=>(x.title+x.kind+x.summary).toLowerCase().includes(query.toLowerCase())):searchEntries,[query]);
  return <div className="search"><Icon name="search"/><input aria-label="Search documentation" placeholder="Search nodes, guides, errors…" value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}}/><kbd>⌘ K</kbd>{open&&<div className="search-popover" role="dialog" aria-label="Local search results"><header><b>Local search</b><button onClick={()=>setOpen(false)} aria-label="Close search">×</button></header>{results.map(x=><button className="search-result" key={x.title} onClick={()=>{onGo(x.page);setOpen(false)}}><span>{x.kind}</span><b>{x.title}</b><small>{x.summary}</small></button>)}<footer>No tracking · Index stays in your browser</footer></div>}</div>;
}
export function TopBar({variant,page,onGo}:{variant:Variant;page:Page;onGo:(p:Page)=>void}) { return <header className="topbar"><button className="brand" onClick={()=>onGo("home")}><span>✦</span>BV <b>NodePack</b></button><div className="context">Documentation <DraftPill/></div><Search onGo={onGo}/><a href="#status">Status</a><button className="mobile-menu" aria-label="Open menu"><Icon name="menu"/></button><em>{variant} · {variantNames[variant]} · {page}</em></header>; }
export function TreeNav({page,onGo}:{page:Page;onGo:(p:Page)=>void}) { return <nav className="tree" aria-label="Documentation"><button className={page==="home"?"selected":""} onClick={()=>onGo("home")}><Icon name="book"/> Overview</button>{navItems.map((x,i)=><button key={`${x}-${i}`} className={`${i===3||i===8?"child":""} ${page==="reference"&&i===8?"selected":""}`} onClick={()=>i===8?onGo("reference"):i===3?onGo("guide"):undefined}>{[0,2,7,13].includes(i)&&<span>⌄</span>}{x}</button>)}</nav>; }
export function MetaRail(){return <aside className="meta-rail"><b>On this page</b>{["Overview","Status & availability","Inputs","Outputs","Behavior","Minimal connections","Known limitations"].map(x=><a key={x} href={`#${x.toLowerCase().replaceAll(" ","-").replace("&","and")}`}>{x}</a>)}<hr/><small>Applies to</small><code>regional-context-v3</code><small>Last checked</small><span>24 Aug 2026</span></aside>}
export function AssetPlaceholder({role="connection"}:{role?:string}) { return <figure className="asset-placeholder"><div className="grid"/><span className="badge">{role}</span><div className="fake-node first"><b>BV Regional Prompt</b><span>BV_REGIONAL</span></div><div className="fake-node second"><b>V3 Consumer</b><span>REGIONAL_CONTEXT</span></div><figcaption><b>Asset pending visual approval</b><span>Stable ID: regional-prompt--{role}--default</span></figcaption></figure>; }
export function KnownIssue(){return <aside className="known"><Icon name="warn"/><div><b>Known issue · collector removed after selection</b><p>The consumer fails closed when a required same-graph collector is missing. Reconnect by stable identity, never by slot position.</p><a>Read troubleshooting details →</a></div></aside>}
export function WorkflowPreview(){const dialog=useRef<HTMLDialogElement>(null);const json='data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify({prototype:true,nodes:[]},null,2));return <section className="workflow"><header><div><p className="eyebrow">DOWNLOADABLE WORKFLOW</p><h2>Regional starter</h2><p>Preview the wiring, then drag the workflow PNG into ComfyUI.</p></div><DraftPill/></header><button className="workflow-preview" onClick={()=>dialog.current?.showModal()} aria-label="Open workflow preview"><WorkflowCanvas/><span>Open accessible lightbox</span></button><div className="downloads"><a download="prototype.json" href={json}><Icon name="download"/> Workflow PNG</a><a download="prototype.json" href={json}><Icon name="download"/> Extracted JSON</a></div><dialog ref={dialog}><button className="close" onClick={()=>dialog.current?.close()} aria-label="Close lightbox">×</button><WorkflowCanvas/><p>Development placeholder · no workflow code is executed.</p></dialog></section>}
function WorkflowCanvas(){return <div className="workflow-canvas"><span className="wf n1">Regional Prompt</span><span className="wf n2">LoRA Collector</span><span className="wf n3">Regional LoRA</span><span className="wf n4">Attention</span><svg viewBox="0 0 800 300"><path d="M170 80 C280 80 230 210 355 210 S480 80 600 80"/><path d="M170 220 C260 220 280 210 355 210"/></svg></div>}
