import React from "react";
import type {Page} from "./main";
import {AssetPlaceholder,DraftPill,Icon,KnownIssue,WorkflowPreview} from "./components";

export function Content({page,onGo}:{page:Page;onGo:(p:Page)=>void}) { return page==="home"?<Home onGo={onGo}/>:page==="reference"?<Reference/>:<Guide/>; }
function Home({onGo}:{onGo:(p:Page)=>void}) { const cards=[["Regional System","Draw, bind and execute spatial prompt contexts.","12 nodes"],["Smart Pipes","Carry typed state across visible and wireless branches.","4 nodes"],["Workflow Control","Coordinate graph stages, seeds and execution states.","5 nodes"],["Prompt Processing","Parse, inspect and route structured prompt blocks.","5 nodes"],["Subgraph Interface","Project headings, dividers and controlled choices.","4 nodes"],["Latent & Utilities","Deterministic sizing, rotation, colors and logs.","6 nodes"]]; return <>
  <section className="hero"><div><DraftPill/><p className="eyebrow">DEEP WORKFLOW TOOLS FOR COMFYUI</p><h1>Build complex workflows<br/><em>without losing the thread.</em></h1><p className="lede">Guided setup, stable contracts and focused reference material for BV NodePack’s regional, structured and reusable workflow systems.</p><div className="hero-actions"><button className="primary" onClick={()=>onGo("guide")}>Start with Regional <Icon name="arrow"/></button><button onClick={()=>onGo("reference")}>Browse node reference</button></div></div><div className="hero-visual"><div className="fake-node h1"><b>Regional Prompt</b><span>regional</span></div><div className="fake-node h2"><b>LoRA Collector</b><span>resources</span></div><div className="fake-node h3"><b>Attention</b><span>conditioning</span></div></div></section>
  <section className="section-head"><div><p className="eyebrow">CHOOSE A SYSTEM</p><h2>Start from what you want to build.</h2></div><p>Task-oriented guides first. Exact contracts when you need them.</p></section>
  <div className="system-grid">{cards.map((c,i)=><button className="system-card" key={c[0]} onClick={()=>i===0&&onGo("guide")}><span className="card-icon"><Icon name={i===1?"flow":"node"}/></span><small>{c[2]}</small><h3>{c[0]}</h3><p>{c[1]}</p><span>Explore system →</span></button>)}</div>
  <section className="status-strip" id="status"><div><i/><b>Development baseline</b><span>Following regional-context-v3</span></div><div><b>58</b><span>nodes inventoried</span></div><div><b>0</b><span>pages approved</span></div></section>
  </>; }
function Reference(){return <article className="doc"><div className="breadcrumbs">Node Reference / Regional Prompting / BV Regional Prompt</div><header className="doc-title"><div><DraftPill/><p className="eyebrow">NODE REFERENCE</p><h1>BV Regional Prompt</h1><p>Author the model-neutral regional document that every V3 execution path consumes.</p></div><span className="node-mark"><Icon name="node"/></span></header><div className="facts"><span><small>Category</small>Regional Prompting</span><span><small>Audience</small>Standard</span><span><small>Status</small>Development</span><span><small>Difficulty</small>Intermediate</span></div><section id="overview"><h2>Overview</h2><p>The node owns prompts, geometry and stable identities. V3 consumers materialize same-graph capabilities without creating a second persistence layer.</p></section><KnownIssue/><section id="inputs"><h2>Inputs</h2><div className="contract"><header><span>Name</span><span>Type</span><span>Required</span><span>Purpose</span></header><div><code>document</code><code>BV_REGIONAL</code><span>Yes</span><span>Canonical regional document</span></div><div><code>context</code><code>REGIONAL_CONTEXT</code><span>No</span><span>Inherited V3 capabilities</span></div></div></section><section id="minimal-connections"><h2>Minimal connections</h2><AssetPlaceholder/></section><section id="known-limitations"><h2>Known limitations</h2><p>Missing required resources fail closed instead of silently using stale selections.</p></section><Pager/></article>}
function Guide(){return <article className="doc"><div className="breadcrumbs">Node Guides / Regional Prompting / First V3 workflow</div><header className="doc-title"><div><DraftPill/><p className="eyebrow">NODE GUIDE · 12 MIN</p><h1>Build your first regional workflow</h1><p>Connect authoring, scoped capabilities and execution without hidden persistence.</p></div></header><aside className="outcome"><small>YOU WILL BUILD</small><b>A two-region attention workflow with one scoped LoRA capability.</b></aside><AssetPlaceholder role="final-connection-preview"/><section><h2>Prerequisites</h2><ul><li>V3 development branch loaded</li><li>Compatible attention backend</li><li>One tested LoRA resource</li></ul></section><section className="steps">{[["01","Add the authoring node","Create BV Regional Prompt and define Global, Background and two regions."],["02","Materialize the capability","Connect BV LoRA Stack Collector and select by stable identities."],["03","Execute the context","Connect the materialized context to a compatible Attention node."]].map(s=><div className="step" key={s[0]}><span>{s[0]}</span><div><h2>{s[1]}</h2><p>{s[2]}</p></div></div>)}</section><KnownIssue/><WorkflowPreview/><Pager/></article>}
function Pager(){return <footer className="pager"><button>← Previous topic</button><button>Next reference →</button></footer>}
