import React from "react";
import type {Page} from "./main";
import {Content} from "./pages";
import {DraftPill,Icon,MetaRail,Search,TopBar,TreeNav} from "./components";

type Props={page:Page;onGo:(p:Page)=>void};
export function VariantA({page,onGo}:Props){return <div className="shell shell-a"><TopBar variant="A" page={page} onGo={onGo}/><aside className="left"><small>DOCUMENTATION</small><TreeNav page={page} onGo={onGo}/><footer>Documentation status <b>V3 · Draft</b></footer></aside><main className="content"><Content page={page} onGo={onGo}/></main>{page!=="home"&&<MetaRail/>}</div>}
export function VariantB({page,onGo}:Props){return <div className="shell shell-b"><TopBar variant="B" page={page} onGo={onGo}/><nav className="atlas"><button onClick={()=>onGo("home")}>Start</button><button onClick={()=>onGo("guide")}>Guides</button><button onClick={()=>onGo("reference")}>Reference</button><button>Recipes</button><button>Compatibility</button></nav><main className="content"><Content page={page} onGo={onGo}/></main>{page!=="home"&&<aside className="atlas-context"><b>Explore this topic</b><button onClick={()=>onGo("guide")}>Regional guide</button><button onClick={()=>onGo("reference")}>Node contract</button><button>Known issues</button></aside>}</div>}
export function VariantC({page,onGo}:Props){return <div className={`shell shell-c ${page!=="home"?"with-toc":""}`}><aside className="icons"><button className="rail-brand" onClick={()=>onGo("home")}>✦</button><button aria-label="Home" onClick={()=>onGo("home")}><Icon name="book"/></button><button aria-label="Guides" onClick={()=>onGo("guide")}><Icon name="flow"/></button><button aria-label="Reference" onClick={()=>onGo("reference")}><Icon name="node"/></button><i/><button aria-label="Menu"><Icon name="menu"/></button></aside><header className="index-head"><div><small>BV NODEPACK / V3</small><b>{page==="home"?"Documentation index":page==="guide"?"Guide workspace":"Contract workspace"}</b></div><Search onGo={onGo}/><DraftPill/></header><aside className="index-nav"><TreeNav page={page} onGo={onGo}/></aside><main className="content"><Content page={page} onGo={onGo}/></main>{page!=="home"&&<MetaRail/>}</div>}
